name: dart_telegram_bot
description: A basic Telegram Bot API wrapper made to make fast Telegram bots with as less code as possible.
version: 0.3.1
homepage: https://github.com/KaikyuDev/dart-telegram-bot

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
