name: dart_telegram_bot
description: A basic Telegram Bot API wrapper made to make fast Telegram bots with as less code as possible.
version: 0.2.0
homepage: https://github.com/KaikyuDev/dart-telegram-bot

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  kson:
    path: "C:/Users/Kaikyu/IdeaProjects/kson"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
